# Generated by Django 5.2.6 on 2025-10-09 05:38

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizationUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/mylocalizationproject_uploads/'), upload_to='pots/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('po_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/mylocalizationproject_uploads/'), upload_to='translations/po/')),
                ('mo_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/mylocalizationproject_uploads/'), upload_to='translations/mo/')),
                ('translated_at', models.DateTimeField(auto_now_add=True)),
                ('edited_content', models.TextField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizationtool.localizationupload')),
            ],
        ),
    ]
