# Generated by Django 5.2.6 on 2025-10-15 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizationtool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationresult',
            name='translated_at',
        ),
        migrations.AlterField(
            model_name='localizationupload',
            name='pot_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='translationresult',
            name='mo_file',
            field=models.FileField(upload_to='translations/'),
        ),
        migrations.AlterField(
            model_name='translationresult',
            name='po_file',
            field=models.FileField(upload_to='translations/'),
        ),
        migrations.AlterField(
            model_name='translationresult',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='localizationtool.localizationupload'),
        ),
    ]
