# Generated by Django 5.2.6 on 2025-10-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizationtool', '0002_remove_translationresult_translated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizationupload',
            name='pot_file',
            field=models.FileField(max_length=500, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='translationresult',
            name='mo_file',
            field=models.FileField(max_length=500, upload_to='translations/'),
        ),
        migrations.AlterField(
            model_name='translationresult',
            name='po_file',
            field=models.FileField(max_length=500, upload_to='translations/'),
        ),
        migrations.AlterField(
            model_name='translationresult',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizationtool.localizationupload'),
        ),
    ]
