# Generated by Django 5.2.6 on 2025-10-16 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizationtool', '0003_alter_localizationupload_pot_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationresult',
            name='translated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
