# Generated by Django 5.2.6 on 2025-10-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizationtool', '0004_translationresult_translated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationresult',
            name='mo_file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='translationresult',
            name='po_file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='translationresult',
            unique_together={('upload', 'language')},
        ),
    ]
