# Generated by Django 4.2.25 on 2025-11-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizationtool', '0006_add_folder_name_safe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizationupload',
            name='folder_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
